### PR TITLE
Merge ASAP

### PR DESCRIPTION
**Pull request by trojan782**

### CODE REVIEW

**Comment by Wondav** [comment]
I no understand what you did, Any description

**Comment by trojan782** [comment]
Merge the changes i made into the main branch you made some mistakes, I created a pull request to fix the errors.

**Comment by trojan782** [comment]
You are not supposed to push the `.env` and the `venv` to github, I have removed them and I created a `.gitignore` file

**Comment by Wondav** [comment]
Thanks, I understand now

**Pull request merged**
